# Generated by Django 4.2.3 on 2023-07-25 11:39

import django.core.validators
from django.db import migrations, models
import finalProject.user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_collectionuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.MinLengthValidator(10), finalProject.user_profile.validators.phone_number_validator]),
        ),
    ]
