# Generated by Django 4.2.3 on 2023-07-25 11:52

import django.core.validators
from django.db import migrations, models
import finalProject.user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_alter_collectionuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), finalProject.user_profile.validators.only_alphabetical_letters]),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Do not show', 'Do not show')], max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.MinLengthValidator(2), finalProject.user_profile.validators.only_alphabetical_letters]),
        ),
        migrations.AlterField(
            model_name='collectionuser',
            name='profile_picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
