# Generated by Django 4.2.3 on 2023-08-05 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import finalProject.yacht.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yacht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(upload_to='')),
                ('style', models.CharField(choices=[('Cruiser', 'Cruiser'), ('Sports cruiser', 'Sports cruiser'), ('Sports fisherman', 'Sports fisherman'), ('Expedition', 'Expedition'), ('Lobster', 'Lobster'), ('Trawler', 'Trawler'), ('Other', 'Other')], max_length=16)),
                ('classification', models.CharField(choices=[('Class A', 'Class A'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3')], max_length=7)),
                ('engines', models.CharField(choices=[('Full-displacement hull', 'Full-displacement hull'), ('Semi-displacement hull', 'Semi-displacement hull'), ('Planing hull', 'Planing hull')], max_length=22)),
                ('yacht_length', models.FloatField(validators=[finalProject.yacht.validators.check_length])),
                ('price', models.FloatField(validators=[finalProject.yacht.validators.check_price])),
                ('very_short_description', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
