# Generated by Django 4.2.3 on 2023-07-25 14:07

from django.db import migrations, models
import finalProject.yacht.validators


class Migration(migrations.Migration):

    dependencies = [
        ('yacht', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yacht',
            name='description',
        ),
        migrations.AddField(
            model_name='yacht',
            name='very_short_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='classification',
            field=models.CharField(choices=[('Class A', 'Class A'), ('Class 1', 'Class 1'), ('Class 2', 'Class 2'), ('Class 3', 'Class 3')], max_length=7),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='engines',
            field=models.CharField(choices=[('Full-displacement hull', 'Full-displacement hull'), ('Semi-displacement hull', 'Semi-displacement hull'), ('Planing hull', 'Planing hull')], max_length=22),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='price',
            field=models.FloatField(validators=[finalProject.yacht.validators.check_price]),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='style',
            field=models.CharField(choices=[('Cruiser ', 'Cruiser '), ('Sports cruiser', 'Sports cruiser'), ('Sports fisherman', 'Sports fisherman'), ('Expedition', 'Expedition '), ('Lobster ', 'Lobster '), ('Trawler ', 'Trawler '), ('Other ', 'Other ')], max_length=16),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='yacht_length',
            field=models.FloatField(validators=[finalProject.yacht.validators.check_length]),
        ),
    ]
