# Generated by Django 4.2.3 on 2023-07-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yacht', '0002_remove_yacht_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yacht',
            name='style',
            field=models.CharField(choices=[('Cruiser', 'Cruiser'), ('Sports cruiser', 'Sports cruiser'), ('Sports fisherman', 'Sports fisherman'), ('Expedition', 'Expedition'), ('Lobster', 'Lobster'), ('Trawler', 'Trawler'), ('Other', 'Other')], max_length=16),
        ),
    ]
