# Generated by Django 4.2.3 on 2023-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField()),
                ('year', models.IntegerField()),
                ('fuel_type', models.CharField()),
                ('top_speed', models.IntegerField()),
                ('emission_standard', models.CharField()),
                ('horse_power', models.IntegerField()),
                ('image', models.URLField()),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
