# Generated by Django 4.2.3 on 2023-07-25 11:28

from django.db import migrations, models
import finalProject.car.validators


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_alter_car_car_type_alter_car_emission_standard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='description',
        ),
        migrations.AddField(
            model_name='car',
            name='model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='short_description',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='emission_standard',
            field=models.CharField(choices=[('Euro I', 'Euro I'), ('Euro II', 'Euro II'), ('Euro III', 'Euro III'), ('Euro IV', 'Euro IV'), ('Euro V', 'Euro V'), ('Euro V+', 'Euro V+')], max_length=8),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(validators=[finalProject.car.validators.horse_power_validator]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(validators=[finalProject.car.validators.price_validator]),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(validators=[finalProject.car.validators.top_speed_validator]),
        ),
    ]
