# Generated by Django 4.2.3 on 2023-07-25 12:57

from django.db import migrations, models
import finalProject.motorbike.validators


class Migration(migrations.Migration):

    dependencies = [
        ('motorbike', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='motorbike',
            name='bike_model',
        ),
        migrations.RemoveField(
            model_name='motorbike',
            name='description',
        ),
        migrations.AddField(
            model_name='motorbike',
            name='bike_type',
            field=models.CharField(choices=[('Scooter', 'Scooter'), ('Chopper', 'Chopper'), ('Sportbike', 'Sportbike'), ('Off-Road', 'Off-Road'), ('Other', 'Other')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorbike',
            name='model',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='motorbike',
            name='short_description',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='emission_standard',
            field=models.CharField(choices=[('Euro I', 'Euro I'), ('Euro II', 'Euro II'), ('Euro III', 'Euro III'), ('Euro IV', 'Euro IV'), ('Euro V', 'Euro V'), ('Euro V+', 'Euro V+')], max_length=8),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='engine_size',
            field=models.IntegerField(validators=[finalProject.motorbike.validators.engine_size_validator]),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='fuel_capacity',
            field=models.IntegerField(validators=[finalProject.motorbike.validators.fuel_capacity_validator]),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('А95Н', 'А95Н'), ('LPG', 'LPG'), ('Electricity', 'Electricity'), ('Other', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='price',
            field=models.FloatField(validators=[finalProject.motorbike.validators.price_validator]),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='top_speed',
            field=models.IntegerField(validators=[finalProject.motorbike.validators.top_speed_validator]),
        ),
        migrations.AlterField(
            model_name='motorbike',
            name='year',
            field=models.IntegerField(validators=[finalProject.motorbike.validators.check_year]),
        ),
    ]
