# Generated by Django 4.2.3 on 2023-08-07 13:31

from django.db import migrations, models
import finalProject.truck.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/trucks')),
                ('model', models.CharField(choices=[('Man', 'Man'), ('Volvo', 'Volvo'), ('Mercedes', 'Mercedes'), ('Scania', 'Scania'), ('Other', 'Other')], max_length=10)),
                ('year', models.IntegerField(validators=[finalProject.truck.validators.check_year])),
                ('truck_mass', models.FloatField(validators=[finalProject.truck.validators.check_mass])),
                ('truck_height', models.FloatField(validators=[finalProject.truck.validators.check_height])),
                ('engine_power', models.FloatField(validators=[finalProject.truck.validators.check_engine])),
                ('price', models.FloatField(validators=[finalProject.truck.validators.check_price])),
                ('very_short_description', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
