# Generated by Django 4.2.3 on 2023-07-24 16:01

import django.core.validators
from django.db import migrations, models
import finalProject.truck.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_type', models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10)),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)])),
                ('year', models.IntegerField(validators=[finalProject.truck.validators.check_year])),
                ('image_url', models.URLField()),
                ('truck_mass', models.FloatField()),
                ('truck_height', models.FloatField()),
                ('engine_power', models.FloatField()),
                ('price', models.FloatField(validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField()),
            ],
        ),
    ]
