# Generated by Django 4.2.3 on 2023-07-25 13:27

from django.db import migrations, models
import finalProject.truck.validators


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='car_type',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='description',
        ),
        migrations.AddField(
            model_name='truck',
            name='short_description',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='truck',
            name='engine_power',
            field=models.FloatField(validators=[finalProject.truck.validators.check_engine]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='model',
            field=models.CharField(choices=[('Man', 'Man'), ('Volvo', 'Volvo'), ('Mercedes', 'Mercedes'), ('Scania', 'Scania'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='truck',
            name='price',
            field=models.FloatField(validators=[finalProject.truck.validators.check_price]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_height',
            field=models.FloatField(validators=[finalProject.truck.validators.check_height]),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_mass',
            field=models.FloatField(validators=[finalProject.truck.validators.check_mass]),
        ),
    ]
