# Generated by Django 4.2.3 on 2023-08-06 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_alter_truck_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='truck',
            old_name='image_url',
            new_name='image',
        ),
    ]
