# Generated by Django 4.2.3 on 2023-07-25 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('truck', '0003_remove_truck_car_type_remove_truck_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truck',
            name='short_description',
        ),
        migrations.AddField(
            model_name='truck',
            name='very_short_description',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
