# Generated by Django 4.2.3 on 2023-07-25 10:33

import django.core.validators
from django.db import migrations, models
import finalProject.car.validators


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Sports Car', 'Sports Car'), ('Pickup', 'Pickup'), ('Crossover', 'Crossover'), ('Minibus', 'Minibus'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='emission_standard',
            field=models.CharField(choices=[('Euro I', 'Euro I'), ('Euro II', 'Euro II'), ('Euro III', 'Euro III'), ('Euro IV', 'Euro IV'), ('Euro V', 'Euro V'), ('Euro V+', 'Euro V+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(choices=[('Diesel', 'Diesel'), ('А95Н', 'А95Н'), ('LPG', 'LPG'), ('Electricity', 'Electricity'), ('Other', 'Other')], max_length=11),
        ),
        migrations.AlterField(
            model_name='car',
            name='horse_power',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='top_speed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.IntegerField(validators=[finalProject.car.validators.check_year]),
        ),
    ]
